# Generated by Django 4.2.30 on 2026-05-02 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='color_accent',
            field=models.CharField(default='#f59e0b', max_length=7, verbose_name='Акцентный цвет'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='color_bg',
            field=models.CharField(default='#f9fafb', max_length=7, verbose_name='Цвет фона'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='color_primary',
            field=models.CharField(default='#2563eb', max_length=7, verbose_name='Основной цвет'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='color_primary_dark',
            field=models.CharField(default='#1d4ed8', max_length=7, verbose_name='Тёмный акцент'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='color_text',
            field=models.CharField(default='#111827', max_length=7, verbose_name='Цвет текста'),
        ),
    ]
