# Generated by Django 4.2.30 on 2026-05-02 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sitesettings_color_accent_sitesettings_color_bg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='color_text_secondary',
            field=models.CharField(default='#6b7280', max_length=7, verbose_name='Вторичный цвет текста'),
        ),
    ]
