# Generated by Django 4.2.30 on 2026-05-02 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sitesettings_color_text_secondary'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='color_card',
            field=models.CharField(default='#ffffff', max_length=7, verbose_name='Цвет карточек'),
        ),
    ]
