# Generated by Django 4.2.30 on 2026-05-02 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_sitesettings_color_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='color_footer_text',
            field=models.CharField(default='#e5e7eb', max_length=7, verbose_name='Цвет текста в подвале'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='color_header_text',
            field=models.CharField(default='#ffffff', max_length=7, verbose_name='Цвет текста в шапке'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='color_text',
            field=models.CharField(default='#111827', max_length=7, verbose_name='Основной цвет текста'),
        ),
    ]
