# Generated by Django 4.2.30 on 2026-05-02 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_sitesettings_color_footer_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='slogan',
            field=models.CharField(blank=True, max_length=255, verbose_name='Слоган'),
        ),
    ]
