# Generated by Django 4.2.30 on 2026-05-03 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_sitesettings_slogan'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('phone', 'Телефон'), ('email', 'Email'), ('address', 'Адрес'), ('map', 'Карта'), ('text', 'Иное'), ('social', 'Соцсеть')], max_length=20, verbose_name='Тип')),
                ('label', models.CharField(help_text='Например: Администратор, Главный офис, ВКонтакте', max_length=255, verbose_name='Описание')),
                ('value', models.TextField(help_text='Номер телефона, email, адрес, ссылка на карту или текст', verbose_name='Значение')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Контактный элемент',
                'verbose_name_plural': 'Контактные элементы',
                'ordering': ['order', 'type'],
            },
        ),
        migrations.DeleteModel(
            name='ContactInfo',
        ),
    ]
