# Generated by Django 4.2.30 on 2026-05-04 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_contactitem_delete_contactinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagesection',
            name='draft_content',
            field=models.JSONField(blank=True, default=dict, verbose_name='Черновик'),
        ),
    ]
