# Generated by Django 4.2.30 on 2026-05-02 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название жанра')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Жанр портфолио',
                'verbose_name_plural': 'Жанры портфолио',
            },
        ),
        migrations.CreateModel(
            name='PortfolioPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='portfolio/original/', verbose_name='Оригинал')),
                ('image_watermarked', models.ImageField(blank=True, null=True, upload_to='portfolio/watermarked/', verbose_name='С водяным знаком')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='portfolio/thumbnails/', verbose_name='Миниатюра')),
                ('filename', models.CharField(max_length=255, unique=True, verbose_name='Имя файла')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='photos', to='portfolio.portfoliogenre', verbose_name='Жанр')),
            ],
            options={
                'verbose_name': 'Фотография портфолио',
                'verbose_name_plural': 'Фотографии портфолио',
                'ordering': ['filename'],
            },
        ),
    ]
