# Generated by Django 4.2.30 on 2026-05-02 00:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255, verbose_name='Имя клиента')),
                ('client_phone', models.CharField(max_length=50, verbose_name='Телефон клиента')),
                ('client_email', models.EmailField(max_length=254, verbose_name='Email клиента')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий клиента')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('awaiting_call', 'Ожидает звонка'), ('confirmed', 'Подтверждена'), ('done', 'Выполнена'), ('cancelled', 'Отменена'), ('no_show', 'Не пришёл')], default='new', max_length=20, verbose_name='Статус')),
                ('manager_note', models.TextField(blank=True, verbose_name='Примечание менеджера')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='services.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkingSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('time_start', models.TimeField(verbose_name='Начало')),
                ('time_end', models.TimeField(verbose_name='Конец')),
                ('is_blocked', models.BooleanField(default=False, verbose_name='Заблокирован')),
                ('block_reason', models.CharField(blank=True, max_length=500, verbose_name='Причина блокировки')),
            ],
            options={
                'verbose_name': 'Временной слот',
                'verbose_name_plural': 'Временные слоты',
                'ordering': ['date', 'time_start'],
                'unique_together': {('date', 'time_start')},
            },
        ),
        migrations.CreateModel(
            name='BookingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(choices=[('new', 'Новая'), ('awaiting_call', 'Ожидает звонка'), ('confirmed', 'Подтверждена'), ('done', 'Выполнена'), ('cancelled', 'Отменена'), ('no_show', 'Не пришёл')], max_length=20, verbose_name='Старый статус')),
                ('new_status', models.CharField(choices=[('new', 'Новая'), ('awaiting_call', 'Ожидает звонка'), ('confirmed', 'Подтверждена'), ('done', 'Выполнена'), ('cancelled', 'Отменена'), ('no_show', 'Не пришёл')], max_length=20, verbose_name='Новый статус')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата изменения')),
                ('client_notified', models.BooleanField(default=False, verbose_name='Клиент уведомлён')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='bookings.booking', verbose_name='Заявка')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Изменил')),
            ],
            options={
                'verbose_name': 'История статуса заявки',
                'verbose_name_plural': 'История статусов заявок',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='bookings.workingslot', verbose_name='Слот'),
        ),
    ]
